Update setup.md
LibraryCarpentry/lc-open-refine pull request #175
Opened 2021-02-12 06:51 UTC by bkmgit

Latest version of OpenRefine is 3.4.1

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

2021-02-12 12:08 UTC, ostephens commented
Thanks for this @bkmgit . Do you know if the lesson has been fully tested with OpenRefine 3.4.1?

2021-04-21 16:54 UTC, LWhit528 requested changes
After the section "Downloading the Data" I recommend the following paragraph (in response to Exiting OpenRefine correctly #177)

###Exiting OpenRefine
To exit OpenRefine, close all the browser tabs or windows, then navigate to the command line window. To close this window and ensure OpenRefine exits properly, hold down [control] and press [c] on your keyboard. This will save all changes to your projects.

2021-04-23 10:46 UTC, ostephens approved these changes

2021-04-23 10:58 UTC, merged

2021-04-23 10:58 UTC, ostephens commented
Thanks @bkmgit for your patience and thanks @LWhit528 for the addition to address #177