Add details to OpenRefine setup as per Issue 234.md
LibraryCarpentry/lc-open-refine pull request #253
Opened 2022-10-26 07:50 UTC by stephanieuwa

Adding details about the command line window when OpenRefine first runs as per Issue #234. As raised in the Issue, the Command Line Window was mentioned in the 'Exit' section, but not introduced at the start of the lesson.

2022-10-26 09:34 UTC, ostephens requested changes
Thanks for this @stephanieuwa - just a couple of minor issues before I think this is ready to merge

2022-10-31 07:08 UTC, stephanieuwa commented on setup.md
> +When running OpenRefine, initially a "Command Line Window" will open. This is a window with a black background. As OpenRefine runs, lines of text will appear in the command line window. Then the Open
Thanks @ostephens, that's really helpful. I've made those edits. I'm still quite new to GitHub so I don't know if there's anything further I need to do to submit those additional edits to you? They appear to be part of this pull request but I'm not 100% certain. Thanks.

2022-10-31 09:16 UTC, ostephens commented on setup.md
> +When running OpenRefine, initially a "Command Line Window" will open. This is a window with a black background. As OpenRefine runs, lines of text will appear in the command line window. Then the Open
Thanks @stephanieuwa - that's exactly the right thing - as soon as you add further edits to the branch you used to create the pull request they appear on the pull request

2022-10-31 09:16 UTC, merged

2022-10-31 09:16 UTC, ostephens commented
Thanks so much @stephanieuwa